apiVersion: v1
entries:
  eventos-backend:
  - apiVersion: v2
    created: "2025-11-21T21:32:19.949659215Z"
    description: Helm chart for Eventos Laravel backend
    digest: 7e465d986384fed91c2627bbdd5bc5869cc3f381ac677033105565abaa28a1c2
    name: eventos-backend
    type: application
    urls:
    - https://jcampos2907.github.io/charts/eventos-backend-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v2
    created: "2025-11-21T21:32:19.954359544Z"
    description: Helm chart for Eventos Laravel backend
    digest: f56abf834a280a5f4942f5f0429129d828275c6d06722f18efbe192326a82d31
    name: eventos-backend
    type: application
    urls:
    - https://jcampos2907.github.io/charts/eventos/eventos-backend-0.1.0.tgz
    version: 0.1.0
  eventos-backend-nginx:
  - apiVersion: v2
    created: "2025-11-21T21:32:19.950044691Z"
    description: Helm chart for Eventos Laravel backend
    digest: 8a6151c0fcfee98e6bfb3d2ae5ac06a3fded1779b8f582abd8b22175f3dddacb
    name: eventos-backend-nginx
    type: application
    urls:
    - https://jcampos2907.github.io/charts/eventos-backend-nginx-0.1.0.tgz
    version: 0.1.0
  medusa:
  - apiVersion: v2
    appVersion: 2.8.4
    created: "2025-11-21T21:32:19.954961285Z"
    description: Medusa server + Redis deployment
    digest: fddab6ed41737c28c610a149d14b04e07c9e4061bf15f5b05649220da3513c1c
    name: medusa
    urls:
    - https://jcampos2907.github.io/charts/eventos/medusa-0.1.0.tgz
    version: 0.1.0
  pihole:
  - apiVersion: v1
    appVersion: 2025.08.0
    created: "2025-11-21T21:32:19.953847888Z"
    description: Highly-available Pi-hole with StatefulSet, Nebula Sync, and optional
      Unbound sidecar
    digest: 49a3ea8524af98e2a315172ee5253327b6d9595e31e9c2b347c36df3745b99e5
    home: https://github.com/MoJo2600/pihole-kubernetes/tree/main/charts/pihole
    icon: https://wp-cdn.pi-hole.net/wp-content/uploads/2016/12/Vortex-R.png
    maintainers:
    - email: christian.erhardt@mojo2k.de
      name: MoJo2600
    name: pihole
    sources:
    - https://github.com/MoJo2600/pihole-kubernetes/tree/main/charts/pihole
    - https://pi-hole.net/
    - https://github.com/pi-hole
    - https://github.com/pi-hole/docker-pi-hole
    urls:
    - https://jcampos2907.github.io/charts/pihole-0.1.0.tgz
    version: 0.1.0
generated: "2025-11-21T21:32:19.949048306Z"
