apiVersion: v1
entries:
  eventos-backend:
  - apiVersion: v2
    created: "2025-12-01T23:27:47.003326782Z"
    description: Helm chart for Eventos Laravel backend
    digest: 2a86331211cc148b44c52ea7a75742644728685e4e3229444d47eb9a80f03902
    name: eventos-backend
    type: application
    urls:
    - https://jcampos2907.github.io/charts/eventos-backend-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v2
    created: "2025-12-01T23:27:47.007566449Z"
    description: Helm chart for Eventos Laravel backend
    digest: f56abf834a280a5f4942f5f0429129d828275c6d06722f18efbe192326a82d31
    name: eventos-backend
    type: application
    urls:
    - https://jcampos2907.github.io/charts/eventos/eventos-backend-0.1.0.tgz
    version: 0.1.0
  eventos-backend-nginx:
  - apiVersion: v2
    created: "2025-12-01T23:27:47.004370147Z"
    description: Helm chart for Eventos Laravel backend
    digest: 8e54a0b14df88001ab11aea6fc72526ea6ddb1d5349bb7c4a26b579def968be5
    name: eventos-backend-nginx
    type: application
    urls:
    - https://jcampos2907.github.io/charts/eventos-backend-nginx-0.1.0.tgz
    version: 0.1.0
  medusa:
  - apiVersion: v2
    appVersion: 2.8.4
    created: "2025-12-01T23:27:47.008003018Z"
    description: Medusa server + Redis deployment
    digest: fddab6ed41737c28c610a149d14b04e07c9e4061bf15f5b05649220da3513c1c
    name: medusa
    urls:
    - https://jcampos2907.github.io/charts/eventos/medusa-0.1.0.tgz
    version: 0.1.0
  pihole:
  - apiVersion: v1
    appVersion: 2025.08.0
    created: "2025-12-01T23:27:47.007109404Z"
    description: Highly-available Pi-hole with StatefulSet, Nebula Sync, and optional
      Unbound sidecar
    digest: a10c0d7cf133cd35e1a7e7e2cf053319684869ad125d9565fe0395b42b81baa3
    home: https://github.com/MoJo2600/pihole-kubernetes/tree/main/charts/pihole
    icon: https://wp-cdn.pi-hole.net/wp-content/uploads/2016/12/Vortex-R.png
    maintainers:
    - email: nacho.campos29@gmail.com
      name: jcampos2907
    name: pihole
    sources:
    - https://github.com/MoJo2600/pihole-kubernetes/tree/main/charts/pihole
    - https://pi-hole.net/
    - https://github.com/pi-hole
    - https://github.com/pi-hole/docker-pi-hole
    urls:
    - https://jcampos2907.github.io/charts/pihole-0.1.0.tgz
    version: 0.1.0
generated: "2025-12-01T23:27:47.002652675Z"
