apiVersion: v1
entries:
  eventos-backend:
  - apiVersion: v2
    created: "2025-11-21T19:00:10.585861989Z"
    description: Helm chart for Eventos Laravel backend
    digest: 54a0b0d7119fb197413e7247f63822d5ebe3b69f253b934ea59a9ed75d9e90d5
    name: eventos-backend
    type: application
    urls:
    - https://jcampos2907.github.io/charts/eventos-backend-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v2
    created: "2025-11-21T19:00:10.588961285Z"
    description: Helm chart for Eventos Laravel backend
    digest: f56abf834a280a5f4942f5f0429129d828275c6d06722f18efbe192326a82d31
    name: eventos-backend
    type: application
    urls:
    - https://jcampos2907.github.io/charts/eventos/eventos-backend-0.1.0.tgz
    version: 0.1.0
  eventos-backend-nginx:
  - apiVersion: v2
    created: "2025-11-21T19:00:10.586229786Z"
    description: Helm chart for Eventos Laravel backend
    digest: bb56f67bd4e35b7a7b79ffd8c82b7698fadbfeb3d60dc78cf49f564f154efc6d
    name: eventos-backend-nginx
    type: application
    urls:
    - https://jcampos2907.github.io/charts/eventos-backend-nginx-0.1.0.tgz
    version: 0.1.0
  medusa:
  - apiVersion: v2
    appVersion: 2.8.4
    created: "2025-11-21T19:00:10.589405286Z"
    description: Medusa server + Redis deployment
    digest: fddab6ed41737c28c610a149d14b04e07c9e4061bf15f5b05649220da3513c1c
    name: medusa
    urls:
    - https://jcampos2907.github.io/charts/eventos/medusa-0.1.0.tgz
    version: 0.1.0
  pihole:
  - apiVersion: v1
    appVersion: 2025.08.0
    created: "2025-11-21T19:00:10.588536324Z"
    description: Highly-available Pi-hole with StatefulSet, Nebula Sync, and optional
      Unbound sidecar
    digest: 569cc64f38e3d31d4c79d4a03f13f7712acdb021a6a6dcf2209da98ba4ce170f
    home: https://github.com/MoJo2600/pihole-kubernetes/tree/main/charts/pihole
    icon: https://wp-cdn.pi-hole.net/wp-content/uploads/2016/12/Vortex-R.png
    maintainers:
    - email: christian.erhardt@mojo2k.de
      name: MoJo2600
    name: pihole
    sources:
    - https://github.com/MoJo2600/pihole-kubernetes/tree/main/charts/pihole
    - https://pi-hole.net/
    - https://github.com/pi-hole
    - https://github.com/pi-hole/docker-pi-hole
    urls:
    - https://jcampos2907.github.io/charts/pihole-0.1.0.tgz
    version: 0.1.0
generated: "2025-11-21T19:00:10.585272918Z"
