apiVersion: v1
entries:
  eventos-backend:
  - apiVersion: v2
    created: "2026-02-19T05:57:10.875577432Z"
    description: Helm chart for Eventos Laravel backend
    digest: 0e4e5c8c254d791c50a3eb5aea4daba564191ee687428c984198fb84a8a44938
    name: eventos-backend
    type: application
    urls:
    - https://jcampos2907.github.io/charts/eventos-backend-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v2
    created: "2026-02-19T05:57:10.88327851Z"
    description: Helm chart for Eventos Laravel backend
    digest: f56abf834a280a5f4942f5f0429129d828275c6d06722f18efbe192326a82d31
    name: eventos-backend
    type: application
    urls:
    - https://jcampos2907.github.io/charts/eventos/eventos-backend-0.1.0.tgz
    version: 0.1.0
  eventos-backend-nginx:
  - apiVersion: v2
    created: "2026-02-19T05:57:10.875896453Z"
    description: Helm chart for Eventos Laravel backend
    digest: d29db8ce089841f0ed957b295cf988461581f393bb13ac3357dd8d5d30189b8f
    name: eventos-backend-nginx
    type: application
    urls:
    - https://jcampos2907.github.io/charts/eventos-backend-nginx-0.1.0.tgz
    version: 0.1.0
  medusa:
  - apiVersion: v2
    appVersion: 2.8.4
    created: "2026-02-19T05:57:10.883805773Z"
    description: Medusa server + Redis deployment
    digest: fddab6ed41737c28c610a149d14b04e07c9e4061bf15f5b05649220da3513c1c
    name: medusa
    urls:
    - https://jcampos2907.github.io/charts/eventos/medusa-0.1.0.tgz
    version: 0.1.0
  pihole:
  - apiVersion: v1
    appVersion: 2025.08.0
    created: "2026-02-19T05:57:10.879595031Z"
    description: Highly-available Pi-hole with StatefulSet, Nebula Sync, and optional
      Unbound sidecar
    digest: 59ca313489e53f32c895ae1d8ea2d1c56482368d6d299df459f5088e9477399e
    home: https://github.com/MoJo2600/pihole-kubernetes/tree/main/charts/pihole
    icon: https://wp-cdn.pi-hole.net/wp-content/uploads/2016/12/Vortex-R.png
    maintainers:
    - email: nacho.campos29@gmail.com
      name: jcampos2907
    name: pihole
    sources:
    - https://github.com/MoJo2600/pihole-kubernetes/tree/main/charts/pihole
    - https://pi-hole.net/
    - https://github.com/pi-hole
    - https://github.com/pi-hole/docker-pi-hole
    urls:
    - https://jcampos2907.github.io/charts/pihole-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v1
    appVersion: 2025.08.0
    created: "2026-02-19T05:57:10.877790335Z"
    description: Highly-available Pi-hole with StatefulSet, Nebula Sync, and optional
      Unbound sidecar
    digest: 12795be3fa3d349dff83723482fc056f6ce1bf42ed9b46c8ba0e960874ff2347
    home: https://github.com/MoJo2600/pihole-kubernetes/tree/main/charts/pihole
    icon: https://wp-cdn.pi-hole.net/wp-content/uploads/2016/12/Vortex-R.png
    maintainers:
    - email: nacho.campos29@gmail.com
      name: jcampos2907
    name: pihole
    sources:
    - https://github.com/MoJo2600/pihole-kubernetes/tree/main/charts/pihole
    - https://pi-hole.net/
    - https://github.com/pi-hole
    - https://github.com/pi-hole/docker-pi-hole
    urls:
    - https://jcampos2907.github.io/charts/pihole-0.1.0.tgz
    version: 0.1.0
  technitium-dns:
  - apiVersion: v2
    appVersion: 14.3.0
    created: "2026-02-19T05:57:10.882904645Z"
    description: A Helm chart for deploying Technitium DNS Server - an open source
      authoritative and recursive DNS server
    digest: 16a4636fa484ee77a2fb4a67a1ae136c9e638901e87e4cdce1182c27871de686
    home: https://technitium.com/dns/
    icon: https://technitium.com/favicon.ico
    maintainers:
    - name: Juan Campos
    name: technitium-dns
    sources:
    - https://github.com/TechnitiumSoftware/DnsServer
    - https://hub.docker.com/r/technitium/dns-server
    type: application
    urls:
    - https://jcampos2907.github.io/charts/technitium-dns-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    appVersion: 14.3.0
    created: "2026-02-19T05:57:10.881886513Z"
    description: A Helm chart for deploying Technitium DNS Server - an open source
      authoritative and recursive DNS server
    digest: b5b38544f17a7383cc117782adf521c833075d98b3001949bbb8aa039c9fd392
    home: https://technitium.com/dns/
    icon: https://technitium.com/favicon.ico
    maintainers:
    - name: Juan Campos
    name: technitium-dns
    sources:
    - https://github.com/TechnitiumSoftware/DnsServer
    - https://hub.docker.com/r/technitium/dns-server
    type: application
    urls:
    - https://jcampos2907.github.io/charts/technitium-dns-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: 14.3.0
    created: "2026-02-19T05:57:10.880353211Z"
    description: A Helm chart for deploying Technitium DNS Server - an open source
      authoritative and recursive DNS server
    digest: b3c9d3bcf551cdc06f8d4a77f4df86ea939e5cd5c16190c1b8b9994e1e0ad9f0
    home: https://technitium.com/dns/
    icon: https://technitium.com/favicon.ico
    maintainers:
    - name: Juan Campos
    name: technitium-dns
    sources:
    - https://github.com/TechnitiumSoftware/DnsServer
    - https://hub.docker.com/r/technitium/dns-server
    type: application
    urls:
    - https://jcampos2907.github.io/charts/technitium-dns-0.1.0.tgz
    version: 0.1.0
generated: "2026-02-19T05:57:10.875001215Z"
